fix(36-notifications): Fix app crashing upon creating notification.
MovnaTeam/movna pull request #38
Opened 2023-09-29 18:58 UTC by ronw98

Change notification icon to better match guidelines.

<img width="427" alt="image" src="https://github.com/MovnaTeam/movna/assets/44091831/994e856e-bb6d-43d1-a1b9-9c47eaa3cc26">
<img width="274" alt="image" src="https://github.com/MovnaTeam/movna/assets/44091831/5c40eec3-d712-4be7-a8f4-1ac7eca394da">

Closes #36

2023-09-30 14:34 UTC, BriceCroix requested changes

2023-09-30 14:34 UTC, BriceCroix commented on .gitignore
Why ? I would rather prefer keeping this versionned for the moment we'll want an IOS version (you know in 10 yers or so)

2023-09-30 16:03 UTC, ronw98 commented on .gitignore
I'm not against having iOS files in the project, but if we must have iOS files I'd rather have a full project rather than 4 files
I can create an issue to initialize the iOS project

2023-09-30 16:10 UTC, ronw98 commented on .gitignore
I created the issue #42 .
I'll create the iOS files and remove them from the `.gitignore` file.

I'll merge this PR unless you see any other change that needs to be made ?

2023-10-14 16:19 UTC, BriceCroix approved these changes

2023-10-14 16:20 UTC, merged